In [29]:
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt

In [2]:
get_set_cookies = pd.read_csv('get_set_cookies.csv')

In [3]:
get_set_cookies = get_set_cookies.drop(columns=['visit_id', 'name', 'value'])

In [5]:
# third party scripts accessed cookies from different domains
diff_domains_subset = get_set_cookies[get_set_cookies.cleaned_host != get_set_cookies.script_host]

In [38]:
diff_domains_subset[:5]

,visit_id,host,name,value,cleaned_host,origin_site,script_host,script_url,cookie_name,cookie_value,type,exp_type,exp_group,exp_index
0,1.0,.webmd.com,AMCV_16AD4362526701720A490D45%40AdobeOrg,-432600572%7CMCIDTS%7C18594%7CvVersion%7C4.5.2,webmd,webmd,adobedtm,assets.adobedtm.com/2c8c1e17b98c/e6d47a9a26c9/...,AMCV_16AD4362526701720A490D45%40AdobeOrg,-432600572%7CMCIDTS%7C18594%7CvVersion%7C4.5.2,set,nyt,t,1
1,1.0,.webmd.com,mbox,session#008c00a7adb142598621f56b2baa7b16#16065...,webmd,webmd,adobedtm,assets.adobedtm.com/2c8c1e17b98c/e6d47a9a26c9/...,mbox,session#008c00a7adb142598621f56b2baa7b16#16065...,set,nyt,t,1
2,1.0,www.webmd.com,mnet_session_depth,1%7C1606506091348,webmd,webmd,media,contextual.media.net/bidexchange.js,mnet_session_depth,1%7C1606506091348,set,nyt,t,1
3,1.0,.webmd.com,_li_dcdm_c,.webmd.com,webmd,webmd,liadm,b-code.liadm.com/a-00xm.min.js,_li_dcdm_c,.webmd.com,set,nyt,t,1
4,1.0,.webmd.com,_lc2_fpi,87ca8f4d258a--01er5kk55nbdhke6vdd9ys5s35,webmd,webmd,liadm,b-code.liadm.com/a-00xm.min.js,_lc2_fpi,87ca8f4d258a--01er5kk55nbdhke6vdd9ys5s35,set,nyt,t,1

In [34]:
counts_all = get_set_cookies.groupby(['type' ,'exp_group', 'origin_site', 'exp_index']).size().reset_index(name='counts')

In [35]:
counts_all_t = counts_all[counts_all.exp_group == 't']
counts_all_c = counts_all[counts_all.exp_group == 'c']

In [47]:
counts_all_t[counts_all_t.origin_site=='nytimes']

    type exp_group origin_site  exp_index  counts
42   get         t     nytimes          1     118
43   get         t     nytimes          2     114
44   get         t     nytimes          3     116
45   get         t     nytimes          4     110
46   get         t     nytimes          5     105
47   get         t     nytimes          6     110
102  set         t     nytimes          1      15
103  set         t     nytimes          2      15
104  set         t     nytimes          3      15
105  set         t     nytimes          4      15
106  set         t     nytimes          5      15
107  set         t     nytimes          6      15

In [48]:
counts_all_c[counts_all_c.origin_site=='nytimes']

   type exp_group origin_site  exp_index  counts
12  get         c     nytimes          1     108
13  get         c     nytimes          2     119
14  get         c     nytimes          3      99
15  get         c     nytimes          4     117
16  get         c     nytimes          5     118
17  get         c     nytimes          6     112
72  set         c     nytimes          1      14
73  set         c     nytimes          2      13
74  set         c     nytimes          3      14
75  set         c     nytimes          4      15
76  set         c     nytimes          5      12
77  set         c     nytimes          6      15

In [46]:
for site in counts_all.origin_site.unique():
    # GET
    get_t = counts_all_t[(counts_all_t.type == 'get') & (counts_all_t.origin_site==site)].counts.tolist()
    get_c = counts_all_c[(counts_all_c.type == 'get') & (counts_all_c.origin_site==site)].counts.tolist()
    print("Get "+site, stats.ttest_ind(get_t, get_c))
    # SET
    set_t = counts_all_t[(counts_all_t.type == 'set') & (counts_all_t.origin_site==site)].counts.tolist()
    set_c = counts_all_c[(counts_all_c.type == 'set') & (counts_all_c.origin_site==site)].counts.tolist()
    print("Set "+site, stats.ttest_ind(set_t, set_c))

Get forbes Ttest_indResult(statistic=0.7506418728461542, pvalue=0.4701624023891545)
Set forbes Ttest_indResult(statistic=0.4123843910676311, pvalue=0.6887592714192237)
Get mayoclinic Ttest_indResult(statistic=12.686959860761025, pvalue=1.7278455855773168e-07)
Set mayoclinic Ttest_indResult(statistic=3.974695172395199, pvalue=0.0026233563229100107)
Get nytimes Ttest_indResult(statistic=0.0, pvalue=1.0)
Set nytimes Ttest_indResult(statistic=2.4445060351935224, pvalue=0.03458134743591227)
Get washingtonpost Ttest_indResult(statistic=0.2512529796408524, pvalue=0.8067061259039356)
Set washingtonpost Ttest_indResult(statistic=0.0, pvalue=1.0)
Get webmd Ttest_indResult(statistic=6.216659253282573, pvalue=9.92707962649681e-05)
Set webmd Ttest_indResult(statistic=6.614342812365001, pvalue=5.969822566722048e-05)

In [28]:
diff_domains_subset.groupby(['origin_site', 'type','exp_group'])['script_host', 'cookie_value'].nunique().reset_index()

       origin_site type exp_group  script_host  cookie_value
0           forbes  get         c           18            57
1           forbes  get         t           18            65
2           forbes  set         c           13            45
3           forbes  set         t           14            61
4       mayoclinic  get         c           17           328
5       mayoclinic  get         t           20           457
6       mayoclinic  set         c            5           212
7       mayoclinic  set         t           10           240
8          nytimes  get         c           10            72
9          nytimes  get         t            9            71
10         nytimes  set         c            7            55
11         nytimes  set         t            7            55
12  washingtonpost  get         c           10            62
13  washingtonpost  get         t           10            63
14  washingtonpost  set         c            4            42
15  washingtonpost  set         t            4            42
16           webmd  get         c           18           839
17           webmd  get         t           29          1295
18           webmd  set         c            9           464
19           webmd  set         t           15           772

In [12]:
summary = diff_domains_subset.groupby(['exp_group', 'origin_site', 'script_host', 'type']).size().reset_index(name="count")

In [13]:
summary_t = summary[summary.exp_group=='t']
summary_c = summary[summary.exp_group=='c']

compared_table = pd.merge(summary_c, summary_t, on=['origin_site', 'script_host', 'type'], how='outer', suffixes=('_control', '_treatment'))

compared_table.fillna(0, inplace=True)

compared_table.drop(columns=['exp_group_control', 'exp_group_treatment'], inplace=True)

In [21]:
compared_table.to_csv('compare_set_get.csv', index=False)

In [65]:
compared_table['diff'] = list(map(lambda a, b: abs(b-a), compared_table.count_control, compared_table.count_treatment))

In [69]:
sort_compare = compared_table.sort_values(by=['origin_site', 'type', 'diff'], ascending=False)

In [76]:
temp = sort_compare.groupby(['origin_site', 'script_host'])['count_control', 'count_treatment'].sum().reset_index()

In [84]:
temp['abs_diff'] = list(map(lambda a, b: abs(b-a), temp.count_control, temp.count_treatment))

In [91]:
temp.sort_values(by=['origin_site','abs_diff'], inplace=True, ascending=False)

In [97]:
temp[temp.origin_site=='webmd'][:5]

   origin_site script_host  count_control  count_treatment  abs_diff
64       webmd    adobedtm         1129.0           2290.0    1161.0
73       webmd      google            0.0            723.0     723.0
79       webmd       media         1499.0           2211.0     712.0
78       webmd       liadm         1489.0           2109.0     620.0
66       webmd   amazonaws          365.0            853.0     488.0

In [58]:
compared_table[(compared_table.origin_site =='washingtonpost') & (compared_table.type=='get')]

,origin_site,script_host,type,count_control,count_treatment,diff
70,washingtonpost,amazon-adsystem,get,56.0,49.0,-7.0
71,washingtonpost,chartbeat,get,78.0,83.0,5.0
73,washingtonpost,criteo,get,78.0,77.0,-1.0
75,washingtonpost,g,get,68.0,64.0,-4.0
76,washingtonpost,go-mpulse,get,80.0,78.0,-2.0
77,washingtonpost,google-analytics,get,77.0,79.0,2.0
79,washingtonpost,googletagmanager,get,134.0,142.0,8.0
81,washingtonpost,parrable,get,78.0,77.0,-1.0
82,washingtonpost,rubiconproject,get,12.0,12.0,0.0
83,washingtonpost,scorecardresearch,get,53.0,59.0,6.0

In [14]:
compared_table[compared_table.count_control > compared_table.count_treatment].shape

(52, 6)

In [15]:
compared_table[compared_table.count_control < compared_table.count_treatment]

,exp_type,origin_site,script_host,type,count_control,count_treatment
3,forbes,forbes,chartbeat,get,22.0,45.0
4,forbes,forbes,chartbeat,set,4.0,6.0
5,forbes,forbes,criteo,get,55.0,73.0
7,forbes,forbes,email,get,32.0,36.0
8,forbes,forbes,email,set,4.0,6.0
9,forbes,forbes,facebook,get,8.0,40.0
10,forbes,forbes,facebook,set,2.0,6.0
11,forbes,forbes,forbesimg,get,37.0,58.0
13,forbes,forbes,g,get,15.0,18.0
14,forbes,forbes,google-analytics,get,25.0,49.0
15,forbes,forbes,google-analytics,set,6.0,12.0
16,forbes,forbes,googletagmanager,get,36.0,61.0
17,forbes,forbes,licdn,get,8.0,22.0
18,forbes,forbes,marketo,get,15.0,40.0
21,forbes,forbes,npttech,set,1.0,3.0
22,forbes,forbes,quantserve,get,12.0,29.0
23,forbes,forbes,quantserve,set,1.0,3.0
25,forbes,forbes,siteintercept,get,11.0,23.0
26,forbes,forbes,siteintercept,set,1.0,2.0
29,forbes,forbes,tinypass,get,20.0,55.0
30,forbes,forbes,tinypass,set,5.0,10.0
31,forbes,mayoclinic,appdynamics,get,98.0,148.0
32,forbes,mayoclinic,ensighten,get,513.0,719.0
35,forbes,mayoclinic,g,get,101.0,267.0
36,forbes,mayoclinic,google-analytics,get,248.0,380.0
37,forbes,mayoclinic,google-analytics,set,17.0,24.0
39,forbes,mayoclinic,googletagmanager,get,24.0,26.0
43,forbes,mayoclinic,medtargetsystem,get,119.0,180.0
44,forbes,mayoclinic,medtargetsystem,set,25.0,30.0
45,forbes,mayoclinic,optimizely,get,118.0,179.0
...,...,...,...,...,...,...
211,forbes,webmd,scorecardresearch,get,0.0,29.0
212,nyt,mayoclinic,ensighten,set,0.0,22.0
213,nyt,mayoclinic,everydayhealth,get,0.0,2.0
214,nyt,mayoclinic,everydayhealth,set,0.0,5.0
215,nyt,mayoclinic,quantserve,get,0.0,25.0
216,nyt,mayoclinic,voicefive,get,0.0,74.0
217,nyt,webmd,doubleverify,get,0.0,143.0
218,nyt,webmd,google,get,0.0,238.0
219,nyt,webmd,googlesyndication,get,0.0,60.0
220,nyt,webmd,googletagmanager,get,0.0,36.0
221,nyt,webmd,mouseflow,get,0.0,37.0
222,nyt,webmd,nanigans,get,0.0,32.0
223,nyt,webmd,nanigans,set,0.0,1.0
224,nyt,webmd,scorecardresearch,get,0.0,32.0
225,nyt,webmd,securedvisit,get,0.0,36.0
226,nyt,webmd,securedvisit,set,0.0,1.0
227,nyt,webmd,voicefive,get,0.0,34.0
228,nyt,webmd,wbmdstatic,get,0.0,209.0
229,washington,mayoclinic,ensighten,set,0.0,25.0
230,washington,mayoclinic,googletagmanager,get,0.0,12.0
231,washington,mayoclinic,quantserve,get,0.0,12.0
232,washington,mayoclinic,quantserve,set,0.0,1.0
233,washington,webmd,google,get,0.0,259.0
234,washington,webmd,google-analytics,get,0.0,24.0
235,washington,webmd,google-analytics,set,0.0,2.0
236,washington,webmd,medscapestatic,get,0.0,32.0
237,washington,webmd,medscapestatic,set,0.0,2.0
238,washington,webmd,wbmdstatic,get,0.0,62.0
239,washington,webmd,wbmdstatic,set,0.0,2.0
240,washington,webmd,zdassets,get,0.0,30.0

In [15]:
set_subset = diff_domains_subset[diff_domains_subset.type=='set'].groupby(['exp_type', 'exp_group', 'exp_index', 'origin_site']).size().reset_index(name="count")

In [16]:
set_subset.to_csv("set_op_count.csv", index=False)

In [17]:
get_subset = diff_domains_subset[diff_domains_subset.type=='get'].groupby(['exp_type', 'exp_group', 'exp_index', 'origin_site']).size().reset_index(name="count")

In [18]:
get_subset.to_csv("get_op_count.csv", index=False)

In [19]:
set_subset

       exp_type exp_group  exp_index     origin_site  count
0        forbes         c          1          forbes     15
1        forbes         c          1      mayoclinic     16
2        forbes         c          1           webmd     27
3        forbes         c          2          forbes     11
4        forbes         c          2      mayoclinic     11
5        forbes         c          2           webmd     32
6        forbes         c          3          forbes      1
7        forbes         c          3      mayoclinic     15
8        forbes         c          3           webmd     29
9        forbes         c          4          forbes      1
10       forbes         c          4      mayoclinic     15
11       forbes         c          4           webmd     32
12       forbes         c          5          forbes     29
13       forbes         c          5      mayoclinic     14
14       forbes         c          5           webmd     39
15       forbes         c          6          forbes     12
16       forbes         c          6      mayoclinic     15
17       forbes         c          6           webmd     39
18       forbes         t          1      mayoclinic     16
19       forbes         t          1           webmd     48
20       forbes         t          2          forbes     24
21       forbes         t          2      mayoclinic     18
22       forbes         t          2           webmd     65
23       forbes         t          3          forbes      1
24       forbes         t          3      mayoclinic     30
25       forbes         t          3           webmd     41
26       forbes         t          4          forbes      1
27       forbes         t          4      mayoclinic     16
28       forbes         t          4           webmd     44
29       forbes         t          5          forbes     29
..          ...       ...        ...             ...    ...
77   washington         c          3      mayoclinic     11
78   washington         c          3  washingtonpost      7
79   washington         c          3           webmd     29
80   washington         c          4      mayoclinic     11
81   washington         c          4  washingtonpost      7
82   washington         c          4           webmd     26
83   washington         c          5      mayoclinic     12
84   washington         c          5  washingtonpost      7
85   washington         c          5           webmd     37
86   washington         c          6      mayoclinic     10
87   washington         c          6  washingtonpost      7
88   washington         c          6           webmd     27
89   washington         t          1      mayoclinic     19
90   washington         t          1  washingtonpost      7
91   washington         t          1           webmd     51
92   washington         t          2      mayoclinic     19
93   washington         t          2  washingtonpost      7
94   washington         t          2           webmd     32
95   washington         t          3      mayoclinic     16
96   washington         t          3  washingtonpost      7
97   washington         t          3           webmd     46
98   washington         t          4      mayoclinic     18
99   washington         t          4  washingtonpost      7
100  washington         t          4           webmd     46
101  washington         t          5      mayoclinic     15
102  washington         t          5  washingtonpost      7
103  washington         t          5           webmd     59
104  washington         t          6      mayoclinic     15
105  washington         t          6  washingtonpost      7
106  washington         t          6           webmd     30

[107 rows x 5 columns]

In [20]:
get_subset

       exp_type exp_group  exp_index     origin_site  count
0        forbes         c          1          forbes     91
1        forbes         c          1      mayoclinic    347
2        forbes         c          1           webmd    512
3        forbes         c          2          forbes     42
4        forbes         c          2      mayoclinic    230
5        forbes         c          2           webmd    588
6        forbes         c          3          forbes      3
7        forbes         c          3      mayoclinic    264
8        forbes         c          3           webmd    626
9        forbes         c          4          forbes      6
10       forbes         c          4      mayoclinic    321
11       forbes         c          4           webmd    639
12       forbes         c          5          forbes    195
13       forbes         c          5      mayoclinic    312
14       forbes         c          5           webmd    737
15       forbes         c          6          forbes     64
16       forbes         c          6      mayoclinic    255
17       forbes         c          6           webmd    819
18       forbes         t          1          forbes      4
19       forbes         t          1      mayoclinic    405
20       forbes         t          1           webmd    959
21       forbes         t          2          forbes    207
22       forbes         t          2      mayoclinic    510
23       forbes         t          2           webmd   1008
24       forbes         t          3          forbes      3
25       forbes         t          3      mayoclinic    598
26       forbes         t          3           webmd    705
27       forbes         t          4          forbes      6
28       forbes         t          4      mayoclinic    377
29       forbes         t          4           webmd   1002
..          ...       ...        ...             ...    ...
78   washington         c          3      mayoclinic    276
79   washington         c          3  washingtonpost    119
80   washington         c          3           webmd    549
81   washington         c          4      mayoclinic    266
82   washington         c          4  washingtonpost    115
83   washington         c          4           webmd    441
84   washington         c          5      mayoclinic    273
85   washington         c          5  washingtonpost    110
86   washington         c          5           webmd    939
87   washington         c          6      mayoclinic    245
88   washington         c          6  washingtonpost    132
89   washington         c          6           webmd    552
90   washington         t          1      mayoclinic    488
91   washington         t          1  washingtonpost    122
92   washington         t          1           webmd    849
93   washington         t          2      mayoclinic    493
94   washington         t          2  washingtonpost    121
95   washington         t          2           webmd    625
96   washington         t          3      mayoclinic    351
97   washington         t          3  washingtonpost    112
98   washington         t          3           webmd    966
99   washington         t          4      mayoclinic    395
100  washington         t          4  washingtonpost    125
101  washington         t          4           webmd    978
102  washington         t          5      mayoclinic    419
103  washington         t          5  washingtonpost    119
104  washington         t          5           webmd   1269
105  washington         t          6      mayoclinic    423
106  washington         t          6  washingtonpost    121
107  washington         t          6           webmd    609

[108 rows x 5 columns]