In [159]:
import numpy as np
import pandas as pd
import sqlite3
import sys
import os

def clean_host(host):
    return host.split('.')[-2]

def get_site(site_url):
    return site_url.split(".")[1]

def is_third_party(origin, cookie_host):
    if origin in cookie_host:
        return False
    return True

In [170]:
sql_file = 'exp-data/nyt-1.sqlite' 
    
###### javascript cookies  ######
query = """SELECT sv.site_url, sv.visit_id,
        jsc.host, jsc.name, jsc.value
        FROM javascript_cookies as jsc LEFT JOIN site_visits as sv
        ON sv.visit_id = jsc.visit_id
        """

conn = sqlite3.connect(sql_file)

cookies = pd.read_sql_query(query, conn)
cookies

DatabaseError: Execution failed on sql 'SELECT sv.site_url, sv.visit_id,
        jsc.host, jsc.name, jsc.value
        FROM javascript_cookies as jsc LEFT JOIN site_visits as sv
        ON sv.visit_id = jsc.visit_id
        ': no such table: javascript_cookies

In [171]:
cookies['origin_site'] = list(map(lambda x: get_site(x), cookies.site_url))
cookies["host"] = list(map(lambda x: clean_host(x), cookies.host.tolist()))
cookies["is_third_party"] = list(map(lambda a, b: is_third_party(a, b), cookies.origin_site, cookies.host))

AttributeError: 'DataFrame' object has no attribute 'site_url'

In [172]:
# 95 unique host -> after clean the host: 67
# cookies.host.unique()

In [173]:
cookies = cookies[["visit_id", "origin_site", "host", "name", "value", "is_third_party"]]

In [164]:
# drop duplicate: 1396 -> 539
cookies = cookies.drop_duplicates().reset_index(drop = True)

In [165]:
cookies

,visit_id,origin_site,host,name,value,is_third_party
0,1,webmd,webmd,__cfduid,de1f86f9e699cddfc6fcaeed623176bae1606506089,False
1,1,webmd,webmd,__cfduid,d8d4ebd1e437ddcb310e31be0d82e1cdb1606506089,False
2,1,webmd,webmd,__cfduid,d5b4e59d78d86d6c5ab29b6c3e948cd431606506089,False
3,1,webmd,webmd,__cfduid,d74794a4d59fa87e1456c8b173f3ff20e1606506089,False
4,1,webmd,webmd,test,cookie,False
...,...,...,...,...,...,...
835,3,nytimes,pubmatic,SPugT,1606506426,True
836,3,nytimes,iasds01,AC,1,True
837,3,nytimes,iasds01,DMADT,n+rOZk98RB69wOmiXlusmA,True
838,3,nytimes,iasds01,UT,"""""",True
839,3,nytimes,pubmatic,PMFREQ_ON,YES,True

In [167]:
# cookies[cookies.is_third_party & (cookies.visit_id == 3)]
cookies[(cookies.visit_id == 3)].shape[0]

139

In [144]:
cookies.groupby('host',as_index=False)["host", "name", "value"].size()

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

host
1rx                 4
3lift               8
acuityplatform      3
addthis             4
adentifi            4
                 ...
webmd             154
yahoo              21
yieldmo             7
youtube             2
zemanta             2
Length: 99, dtype: int64

In [142]:
# make sure to use brackets when filtering visit_id == 3
temp = cookies[(cookies.visit_id == 3) & cookies.is_third_party]
temp.groupby('host',as_index=False)["host", "name", "value"].size().nlargest(5)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  This is separate from the ipykernel package so we can avoid doing imports until

host
pubmatic          18
rubiconproject    14
media              8
adsrvr             7
casalemedia        5
dtype: int64

In [131]:
cookies.groupby('origin_site')["host", "name", "value"].nunique()

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

             host  name  value
origin_site
mayoclinic     11    47     76
nytimes        25    80     94
webmd          57   186    322

In [20]:
# cookies.groupby('origin_site').size()

In [16]:
# big_table = []

# data_path = "exp-data/"

# def extract_unique_cookie_pairs(type_name, exp_group, exp_num):
#     file_name = type_name + '-' + exp_group + str(exp_num)
#     print(file_name)
#     conn = sqlite3.connect(data_path + file_name +".sqlite")
#     javascript_cookies = pd.read_sql_query(
#     "select visit_id, host, name, value from javascript_cookies;", conn)
#     javascript_cookies = javascript_cookies.drop_duplicates()
#     df = javascript_cookies.groupby('visit_id')["host", "name", "value"].nunique()
#     pairs = javascript_cookies.groupby('visit_id').size().values
#     df["pairs"] = pairs
#     df['origin_site'] = ['webmd', 'mayoclinic', type_name]
#     df['exp_type'] = [type_name] * 3
#     df['exp_group'] = [exp_group] * 3
#     df['exp_index'] = [exp_num] * 3
#     return df

In [19]:
# exp_types = ['nyt', 'forbes', 'washington']
# exp_groups = ['t', 'c']
# for i in range(1, 7):
#     for t in exp_types:
#         for g in exp_groups:
#             big_table.append(extract_unique_cookie_pairs(t, g, i))

In [18]:
# result = pd.concat(big_table)

In [21]:
# result.to_csv("cookie_result-6.csv", index=False)

In [20]:
# result

,host,name,value,pairs,origin_site,exp_type,exp_group,exp_index
visit_id,,,,,,,,
1,78,190,355,394,webmd,nyt,t,1
2,85,168,278,312,mayoclinic,nyt,t,1
3,43,118,125,139,nyt,nyt,t,1
1,74,186,322,351,webmd,nyt,c,1
2,17,47,76,88,mayoclinic,nyt,c,1
3,33,80,94,100,nyt,nyt,c,1
1,80,204,351,389,webmd,forbes,t,1
2,76,153,237,265,mayoclinic,forbes,t,1
3,82,225,251,305,forbes,forbes,t,1
1,75,189,295,331,webmd,forbes,c,1
2,42,100,133,158,mayoclinic,forbes,c,1
3,84,226,257,299,forbes,forbes,c,1
1,91,202,348,390,webmd,washington,t,1
2,99,197,332,368,mayoclinic,washington,t,1
3,28,73,117,127,washington,washington,t,1
1,74,190,270,305,webmd,washington,c,1
2,14,39,78,87,mayoclinic,washington,c,1
3,28,69,89,100,washington,washington,c,1
1,76,182,358,392,webmd,nyt,t,2
2,80,158,271,300,mayoclinic,nyt,t,2
3,38,105,112,125,nyt,nyt,t,2
1,81,196,318,356,webmd,nyt,c,2
2,17,45,78,85,mayoclinic,nyt,c,2
3,36,101,107,119,nyt,nyt,c,2
1,54,141,270,288,webmd,forbes,t,2
2,81,160,271,303,mayoclinic,forbes,t,2
3,82,223,253,295,forbes,forbes,t,2
1,78,191,269,299,webmd,forbes,c,2
2,19,49,81,92,mayoclinic,forbes,c,2
3,82,218,249,293,forbes,forbes,c,2
...,...,...,...,...,...,...,...,...
1,75,187,338,373,webmd,forbes,t,5
2,98,237,366,424,mayoclinic,forbes,t,5
3,83,227,251,297,forbes,forbes,t,5
1,72,191,316,349,webmd,forbes,c,5
2,29,72,103,124,mayoclinic,forbes,c,5
3,73,200,227,269,forbes,forbes,c,5
1,81,215,388,429,webmd,washington,t,5
2,92,225,344,391,mayoclinic,washington,t,5
3,32,92,141,155,washington,washington,t,5
1,79,212,317,361,webmd,washington,c,5
2,17,43,75,87,mayoclinic,washington,c,5
3,34,94,139,150,washington,washington,c,5
1,71,170,302,329,webmd,nyt,t,6
2,56,115,164,183,mayoclinic,nyt,t,6
3,36,96,105,116,nyt,nyt,t,6
1,76,185,274,306,webmd,nyt,c,6
2,26,68,124,140,mayoclinic,nyt,c,6
3,36,98,110,119,nyt,nyt,c,6
1,68,172,300,325,webmd,forbes,t,6
2,82,165,291,325,mayoclinic,forbes,t,6
3,82,225,251,299,forbes,forbes,t,6
1,76,197,314,350,webmd,forbes,c,6
2,21,51,84,94,mayoclinic,forbes,c,6
3,78,219,240,283,forbes,forbes,c,6
1,65,162,251,281,webmd,washington,t,6
2,55,108,168,187,mayoclinic,washington,t,6
3,34,94,108,121,washington,washington,t,6
1,82,201,295,339,webmd,washington,c,6
2,17,44,79,93,mayoclinic,washington,c,6
3,34,93,154,167,washington,washington,c,6